/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f411retx.h"

int main(void)
{

	//1. enable the clock for GPIOA in AHB1ENR
	// no la vi tri bit thu 1
	RCC_AHB1ENR |= (1<<0);

	//2. configure GPIOA mode as output
	//a, clear 11 and 10 pin to 0
	GPIOA_MODER &= ~(1<<10);
	GPIOA_MODER &= ~(1<<11);
	//b, set 10 to 1
	GPIOA_MODER |= (1<<10);
	//3. Set PA5 pin to output data register to make i/o pin 5 -> HIGH = set 5 to 1

	// turn on and off between 0.56s
	// t = (so vong lap + so cycle/vong) + CPU (Hz)
	while(1){
	GPIOA_ODR |= (1<<5); // turn on led
	// this loop excute 10.000 times
	for(uint32_t i = 0; i < 600000; i++);

	GPIOA_ODR &= ~(1<<5); // turn off led

	for(uint32_t i = 0; i < 600000; i++);
	// khi dung vong lap nay, cpu se bi chiem dung bo nho
	// khong lam duoc gi khac (nhan tin hieu, xu ly)
	// cach nay thuc su khong toi uu
	}
}













